window.MISSDILL_DATA = {
  miniProgram: {
    name: "MissDill",
    status: "pending_real_appid",
    appId: "",
    handoffVersion: "2026-04-28-sprint2",
    cartPath: "/pages/cart/cart",
    fallbackMessage:
      "小程序页面路径已和官网商品数据对齐；真实 AppID 和 URL Scheme 确认后，这里即可发起正式跳转。",
  },
  filters: [
    { id: "all", label: "推荐" },
    { id: "spring", label: "春日限定" },
    { id: "gift", label: "生日祝福" },
    { id: "event", label: "开业乔迁" },
    { id: "class", label: "课程预约" },
  ],
  products: [
    {
      id: "spring-pink-bouquet",
      name: "春日浅粉花束",
      categories: ["spring", "gift"],
      description: "温柔粉系 · 雏菊玫瑰",
      detail:
        "适合生日、纪念日和日常赠礼。整体以浅粉、奶白和自然绿色为主，保留 MissDill 偏自然的松弛花型。",
      price: 398,
      priceLabel: "¥398",
      image: "./assets/product-spring-bouquet.png",
      alt: "春日浅粉花束",
      actionLabel: "加入",
      availability: "当日花材需提前确认",
      deliveryNotes: "建议提前 1 天预约；同城配送范围和时段以小程序为准。",
      miniProgramPath: "/pages/product/detail?id=spring-pink-bouquet",
    },
    {
      id: "fresh-green-basket",
      name: "清新绿意花篮",
      categories: ["spring", "event"],
      description: "自然清新 · 送礼佳选",
      detail:
        "更适合开业、乔迁、探访或空间陈列。用白绿花材营造干净、舒展的视觉，风格克制不喧闹。",
      price: 498,
      priceLabel: "¥498",
      image: "./assets/product-green-basket.png",
      alt: "清新绿意花篮",
      actionLabel: "加入",
      availability: "可做同风格替换",
      deliveryNotes: "花篮尺寸和主花材可按预算微调。",
      miniProgramPath: "/pages/product/detail?id=fresh-green-basket",
    },
    {
      id: "dyed-lily-bouquet",
      name: "吸色百合花束",
      categories: ["spring", "gift"],
      description: "高级配色 · 气质优雅",
      detail:
        "围绕吸色百合做主视觉，适合喜欢特别花材和冷暖混合配色的客人。需要根据当季到货情况确认。",
      price: 598,
      priceLabel: "¥598",
      image: "./assets/product-lily-bouquet.png",
      alt: "吸色百合花束",
      actionLabel: "加入",
      availability: "限量花材",
      deliveryNotes: "吸色花材存在自然色差，下单前建议沟通当天状态。",
      miniProgramPath: "/pages/product/detail?id=dyed-lily-bouquet",
    },
    {
      id: "morandi-pink-bouquet",
      name: "莫兰迪粉色花束",
      categories: ["gift", "event"],
      description: "轻柔雅致 · 氛围感",
      detail:
        "低饱和粉色与自然枝条结合，适合纪念日、拍照、餐桌布置和轻量活动花礼。",
      price: 458,
      priceLabel: "¥458",
      image: "./assets/product-rose-vase.png",
      alt: "莫兰迪粉色花束",
      actionLabel: "加入",
      availability: "稳定供应",
      deliveryNotes: "可按偏粉、偏白、偏绿三个方向微调。",
      miniProgramPath: "/pages/product/detail?id=morandi-pink-bouquet",
    },
    {
      id: "basic-floral-class",
      name: "基础花艺沙龙",
      categories: ["class"],
      description: "2.5 小时 · 小班体验",
      detail:
        "适合第一次接触花艺的客人。课程会覆盖花材认知、基础修剪、构图和包装，完成一份可带走作品。",
      price: 268,
      priceLabel: "¥268",
      image: "./assets/class-workshop.png",
      alt: "花艺沙龙课程",
      actionLabel: "预约",
      availability: "需确认课表",
      deliveryNotes: "课程日期、人数和作品主题以当期发布为准。",
      miniProgramPath: "/pages/class/detail?id=basic-floral-class",
    },
    {
      id: "event-floral-installation",
      name: "活动花艺布置",
      categories: ["event"],
      description: "婚礼 · 小型活动 · 商业空间",
      detail:
        "面向小型婚礼、品牌活动、商业空间和长期陈列。根据场地、预算和花材季节性给出方案。",
      price: 1200,
      priceLabel: "¥1200 起",
      image: "./assets/atelier-courtyard.png",
      alt: "工作室庭院与活动花艺布置",
      actionLabel: "咨询",
      availability: "按项目报价",
      deliveryNotes: "建议至少提前 7 天沟通场地、预算和搭建时间。",
      miniProgramPath: "/pages/custom/event?id=event-floral-installation",
    },
  ],
  videos: {
    feature: {
      id: "atelier-video",
      label: "Lovart Generated",
      title: "一支花束从工作台到交付",
      summary:
        "用 6-8 秒短视频承接首屏氛围：花材、丝带、工作台、小院绿意，适合放在官网、视频号和小红书封面流。",
      src: "./assets/missdill-atelier-video.mp4",
      poster: "./assets/inspiration-bouquet.png",
    },
    stories: [
      {
        title: "吸色百合的独特魅力",
        meta: "花材知识 · 15 秒",
        image: "./assets/inspiration-lily.png",
        alt: "吸色百合花材",
      },
      {
        title: "花艺布置现场记录",
        meta: "活动案例 · 30 秒",
        image: "./assets/inspiration-installation.png",
        alt: "花艺布置现场",
      },
      {
        title: "工作室日常 Vlog",
        meta: "绿墙小院 · 20 秒",
        image: "./assets/inspiration-studio.png",
        alt: "工作室日常 vlog",
      },
    ],
  },
};
